root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main cmd/go-fullstack/main.go"
  delay = 1000
  exclude_dir = ["public", "tmp", "vendor", "test"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "js", "css"]
  include_file = []
  kill_delay = 5000
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  pre_cmd = []
  post_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = true 
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = true 

[screen]
  clear_on_rebuild = false
  keep_scroll = true
