#!/usr/bin/env sh

pattern="go-fullstack"
project_name=$(basename "$PWD")

grep --exclude-dir="scripts" --exclude-dir=".git" -rl $pattern . | while IFS= read -r file; do
    sed -i "s/$pattern/$project_name/g" "$file"
    echo "Replaced $pattern with $project_name in $file"
done

find . -type d -name "*$pattern*" | while IFS= read -r dir; do
    new_name=$(echo "$dir" | sed "s/$pattern/$project_name/")
    mv "$dir" "$new_name"
    echo "Renamed $dir to $new_name"
done

echo "Finished"
